// <auto-generated />
using System;
using MagicCottage_CottageAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicCottage_CottageAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230728152146_SeedCottageTableWithCreatedDate")]
    partial class SeedCottageTableWithCreatedDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicCottage_CottageAPI.Models.Cottage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cottages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 7, 28, 18, 21, 46, 697, DateTimeKind.Local).AddTicks(3152),
                            Details = "Featuring accommodation with a balcony, Royal Cottage Apartments is located in Ureki in the Guria Region. It features a garden and free private parking.",
                            ImageUrl = "https://avatars.mds.yandex.net/get-altay/3923637/2a0000017643b0ca787d1c5f0e0a4f99e929/XXL",
                            Name = "Royal Cottage",
                            Occupancy = 5,
                            Rate = 200,
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 7, 28, 18, 21, 46, 697, DateTimeKind.Local).AddTicks(3169),
                            Details = "Enjoy breathtaking views and serene surroundings at Cottage Hillside. This cozy retreat nestled amidst lush green hills offers a perfect getaway for nature lovers.",
                            ImageUrl = "https://example.com/cottage-hillside.jpg",
                            Name = "Cottage Hillside",
                            Occupancy = 4,
                            Rate = 150,
                            Sqft = 600,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 7, 28, 18, 21, 46, 697, DateTimeKind.Local).AddTicks(3171),
                            Details = "Escape to the tranquility of Lakeside Retreat Cottage, located by a picturesque lake. Indulge in fishing, boating, and relaxing walks along the scenic trails.",
                            ImageUrl = "https://example.com/lakeside-retreat-cottage.jpg",
                            Name = "Lakeside Retreat Cottage",
                            Occupancy = 6,
                            Rate = 180,
                            Sqft = 700,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 7, 28, 18, 21, 46, 697, DateTimeKind.Local).AddTicks(3174),
                            Details = "Experience rustic charm at its best in Cozy Woods Cabin. Nestled deep within a forested area, this cabin offers peace and seclusion away from the hustle and bustle of city life.",
                            ImageUrl = "https://example.com/cozy-woods-cabin.jpg",
                            Name = "Cozy Woods Cabin",
                            Occupancy = 5,
                            Rate = 190,
                            Sqft = 500,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 7, 28, 18, 21, 46, 697, DateTimeKind.Local).AddTicks(3176),
                            Details = "Unwind with stunning ocean views at Seaside Escape Bungalow. This charming bungalow is just steps away from the sandy beach, offering a perfect retreat for beach lovers.",
                            ImageUrl = "https://example.com/seaside-escape-bungalow.jpg",
                            Name = "Seaside Escape Bungalow",
                            Occupancy = 2,
                            Rate = 250,
                            Sqft = 400,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
